### ISSUE TITLE
Support importing typedefs

### ISSUE THREAD

**Issue by OmgImAlexis** [onury/jsdoc-x#12]
I get this error. The import syntax is valid in jsdoc.

```
Error: ERROR: Unable to parse a tag's type expression for source file ~/core/bus.js in line 6 with tag title "param" and text "{import('nanobus')} NanoBus": Invalid type expression "import('nanobus')": Expected "!", "=", "?", "[]", "|", or end of input but "(" found.
```

```js
/**
 * Main event bus.
 *
 * @name Bus
 * @param {import('nanobus')} NanoBus
 * @returns {import('nanobus')}
 */
module.exports = function(NanoBus) {
	return NanoBus;
};
```

Ref: https://github.com/onury/docma/issues/97

**Comment by onury** [comment]
Can you show me how that syntax is valid in JSDoc.
This is the official documentation of JSDoc: https://jsdoc.app
There is no `@import` tag or that syntax.

And the error you get is produced by the underlying JSDoc core, not jsdoc-x itself.

**Comment by OmgImAlexis** [comment]
It's typescript specific but still valid jsdoc. Jsdoc does infact support typescript.

**Comment by onury** [comment]
Sorry but no JSDoc does not support typescript.
You need either a plugin for JSDoc or use a tool that supports [TSDoc](https://github.com/microsoft/tsdoc).

Or you could pass the transpiled .js files to jsdoc-x (that's how I document my typescript projects).

**Comment by DesignByOnyx** [comment]
Wanted to hopefully save someone some time: use [TypeDoc](https://typedoc.org/). It's based on the TSDoc standard, it looks/feels very modern, and it's super simple to use.

**Comment by caph1993** [comment]
This plugin solves this problem: https://github.com/polyforest/jsdoc-tsimport-plugin/

**Comment by AbidKhairyAK** [comment]
> This plugin solves this problem: https://github.com/polyforest/jsdoc-tsimport-plugin/

HOLY COW!!! thank yo so much @caph1993 this fixed my issue
