### ISSUE TITLE
How to use decorators with JSDoc ?

### ISSUE THREAD

**Issue by HamedFathi** [onury/jsdoc-x#6]
Hi
I want to comment on a field with decorator like
```js
class Point {
  constructor(x, y) {
    // ...
  }

  /**
   * a variable with decorator
   */
  @test() val;

  getX() {
    // ...
  }

  getY() {
    // ...
  }

  static fromString(str) {
    // ...
  }
}
```
but I got an error

`Stage 2 decorators may only be used with a class or a class method (10:2)`

How to fix it? Is it possible to comment on decorators ? How to config JSDoc Babel parser for this use case?

**Comment by onury** [comment]
Pls ask this on the JSDoc repo or better on Stackoverflow.
